apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: day4phanipod11
    x: phanijenkins    
  name: day4phanipod11
  namespace: phanins
spec:
  containers:
  - image: phaniazureregistry.azurecr.io/eywebapptest:5
    name: day4phanipod11
    ports:
     - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: day4phanijensvc
  name: day4phanijensvc
  namespace: phanins
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: phanijenkins #same as pod label
  type: ClusterIP
